from fastapi import status

OK = status.HTTP_200_OK
USER_NOT_FOUND = status.HTTP_404_NOT_FOUND
INCORRECT_CREDENTIALS = status.HTTP_401_UNAUTHORIZED
BLOCKED_USER = status.HTTP_403_FORBIDDEN
BAD_REQUEST = status.HTTP_400_BAD_REQUEST
